services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:${PGDATA}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_NAME}"]
      interval: 4s
      timeout: 3s
      retries: 10

  goserver:
    build: .
    container_name: goserver
    depends_on:
      db:
        condition: service_healthy
    expose:
      - 8080
    ports:
      - "8080:8080" 

volumes: 
  pg_data:         